export enum Routes {
  authRouter = 'authRouter',
  mainRouter = 'mainRouter',
  welcome = 'welcome',
  login = 'login',
  register = 'register',
  verification = 'verification',
  paymentMethod = 'paymentMethod',
  resetPassword = 'resetPassword',
  test = 'test',
  home = 'home',
  notification = 'notification',
  account = 'account',
  discovery = 'discovery',
  bookmark = 'bookmark',
  tabNavigator = 'tabNavigator',
}
